config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  authenticate :user, ->(u) { u.admin? } do
    mount PgHero::Engine => '/admin/postgres'
    mount Rollout::UI::Web.new => '/admin/rollout'
    mount Sidekiq::Web => '/admin/sidekiq'
  end

  namespace :admin do
    resources :alliances, only: %i[index show destroy]
    resources :characters, only: %i[index show destroy]
    resources :corporations, only: %i[index show destroy]
    resources :deliveries, only: %i[index show destroy]
    resources :users

    root to: 'dashboard#index'
  end

  devise_for :user, path: '', controllers: { omniauth_callbacks: 'oauth_callbacks' }
  devise_scope :user do
    delete 'auth/logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  get '/healthz', to: 'health#show', as: :health

  get '/dashboard', to: 'dashboard#index'

  resources :characters, only: %i[index show] do
    resources :progressions, only: %i[index show]
  end

  resources :corporations, only: %i[index show edit update], path_names: { edit: 'settings' } do
    resources :authorizations, only: %i[index destroy update], controller: :corporation_authorizations
    resources :members, only: %i[index], controller: :corporation_members
  end

  resources :series do
    member do
      delete :trash
      put :pause
      put :start
    end

    resources :steps, controller: :series_steps do
      member do
        put :move
      end
    end

    resources :subscriptions, controller: :series_subscriptions, only: %i[index show]
  end

  resource :user, path: 'settings', only: %i[show update destroy] do
    resources :characters, only: %i[index create update destroy], controller: :user_characters
  end

  root to: 'landing#index'
end

app/models/user_character.rb
# frozen_string_literal: true

# ## Schema Information
#
# Table name: `user_characters`
#
# ### Columns
#
# Name                | Type               | Attributes
# ------------------- | ------------------ | ---------------------------
# **`id`**            | `bigint`           | `not null, primary key`
# **`main`**          | `boolean`          | `default(FALSE), not null`
# **`created_at`**    | `datetime`         | `not null`
# **`updated_at`**    | `datetime`         | `not null`
# **`character_id`**  | `bigint`           | `not null`
# **`user_id`**       | `bigint`           | `not null`
#
# ### Indexes
#
# * `index_unique_user_character_mains` (_unique_):
#     * **`character_id`**
#     * **`main`**
# * `index_unique_user_characters` (_unique_):
#     * **`character_id`**
# * `index_user_characters_on_character_id`:
#     * **`character_id`**
# * `index_user_characters_on_user_id`:
#     * **`user_id`**
#
# ### Foreign Keys
#
# * `fk_rails_...`:
#     * **`character_id => characters.id`**
# * `fk_rails_...`:
#     * **`user_id => users.id`**
#
class UserCharacter < ApplicationRecord
  belongs_to :character, inverse_of: :user_character
  belongs_to :user, inverse_of: :user_characters, touch: true

  has_one :corporation, through: :character

  delegate :authorized?, :name, to: :character, prefix: true
  delegate :name, to: :corporation, prefix: true
end

app/controllers/user_characters_controller.rb
# frozen_string_literal: true

class UserCharactersController < AuthenticatedController
  before_action :find_user_character, only: %i[destroy]

  layout 'user_settings'

  def index
    @user_characters = current_user.user_characters
  end

  def create
    authorize(current_user.user_characters)

    state = session['omniauth.state'] = SecureRandom.hex
    redirect_to oauth.auth_code.authorize_url(redirect_uri: redirect_uri, scope: scopes, state: state)
  end

  def destroy
    if params[:id].to_i == current_user.main_character_id
      remove_api_access(@user_character)
    else
      @user_character.destroy
      flash[:success] = 'Character successfully removed.'
    end

    redirect_to settings_characters_path
  end

  private

  def remove_api_access(user_character)
    if DestroyAuthorization.new(user_character.character_id).destroy
      flash[:success] = 'Successfully removed API access from main character.'
    else
      flash[:error] = 'Error removing API access from main character.'
    end
  end

  def find_user_character
    @user_character = current_user.user_characters.find_by!(character_id: params[:id])
  end

  def oauth
    @oauth = OAuth2::Client.new(
      Rails.application.config.x.esi.client_id,
      Rails.application.config.x.esi.client_secret,
      site: Rails.application.config.x.esi.oauth_url
    )
  end

  def redirect_uri
    Rails.application.config.x.esi.redirect_uri
  end

  def scopes
    Rails.application.config.x.esi.scopes.join(' ')
  end
end

app/helpers/user_characters_helper.rb
# frozen_string_literal: true

module UserCharactersHelper
end

app/views/user_characters/index.html.erb
<div class="divide-y divide-gray-200 lg:col-span-9">
  <div class="py-6 px-4 sm:p-6 lg:pb-8">
    <div class="flex items-center justify-between flex-wrap sm:flex-nowrap">
      <div>
        <h2 class="text-lg leading-6 font-medium text-gray-900">
          Characters
        </h2>
      </div>
      <div class="flex-shrink-0">
        <%= form_with url: character_settings_path do |f| %>
          <%= f.submit 'Authorize character', class: 'relative inline-flex items-center px-4 py-2 border border-transparent shadow-sm cursor-pointer text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500' %>
        <% end %>
      </div>
    </div>
    <div class="flex flex-col mt-6">
      <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
          <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
            <table class="min-w-full divide-y divide-gray-200">
              <thead class="bg-gray-50">
                <tr>
                  <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Name
                  </th>
                  <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Status
                  </th>
                  <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Last Sync
                  </th>
                  <th scope="col" class="relative px-6 py-3">
                    <span class="sr-only">Edit</span>
                  </th>
                </tr>
              </thead>
              <tbody class="bg-white divide-y divide-gray-200">
                <% @user_characters.each do |uc| %>
                  <tr>
                    <td class="px-6 py-4 whitespace-nowrap">
                      <div class="flex items-center">
                        <div class="flex-shrink-0 h-10 w-10">
                          <%= image_tag eve_character_image_url(uc.character_id, 256), class: 'h-10 w-10 rounded-full' %>
                        </div>
                        <div class="ml-4">
                          <div class="text-sm font-medium text-gray-900">
                            <%= uc.character_name %>
                          </div>
                          <div class="text-sm text-gray-500">
                            <%= uc.corporation_name %>
                          </div>
                        </div>
                      </div>
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap">
                      <% if uc.main? %><span class="ml-2 px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">Main</span><% end %>
                      <% if uc.character_authorized? %><span class="ml-2 px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-blue-100 text-blue-800">Authorized</span><% end %>
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                      <%= local_time uc.updated_at %>
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                      <%= form_with url: character_setting_path(uc.character_id), html: { method: :delete } do |f| %>
                        <%= f.button class: 'relative inline-flex items-center px-2 py-2 text-sm font-medium text-red-500 bg-red border border-red-300 rounded-md hover:bg-red-50 focus:z-10 focus:outline-none focus:ring-1 focus:ring-red-500 focus:border-red-500' do %>
                          <span class="sr-only">Delete</span>
                          <%= render partial: 'icons/solid/x-circle', locals: { w: 5, h: 5, color: 'gray' } %>
                        <% end %>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>