config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  authenticate :user, ->(u) { u.admin? } do
    mount PgHero::Engine => '/admin/postgres'
    mount Rollout::UI::Web.new => '/admin/rollout'
    mount Sidekiq::Web => '/admin/sidekiq'
  end

  namespace :admin do
    resources :alliances, only: %i[index show destroy]
    resources :characters, only: %i[index show destroy]
    resources :corporations, only: %i[index show destroy]
    resources :deliveries, only: %i[index show destroy]
    resources :users

    root to: 'dashboard#index'
  end

  devise_for :user, path: '', controllers: { omniauth_callbacks: 'oauth_callbacks' }
  devise_scope :user do
    delete 'auth/logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  get '/healthz', to: 'health#show', as: :health

  get '/dashboard', to: 'dashboard#index'

  resources :characters, only: %i[index show] do
    resources :progressions, only: %i[index show]
  end

  resources :corporations, only: %i[index show edit update], path_names: { edit: 'settings' } do
    resources :authorizations, only: %i[index destroy update], controller: :corporation_authorizations
    resources :members, only: %i[index], controller: :corporation_members
  end

  resources :series do
    member do
      delete :trash
      put :pause
      put :start
    end

    resources :steps, controller: :series_steps do
      member do
        put :move
      end
    end

    resources :subscriptions, controller: :series_subscriptions, only: %i[index show]
  end

  resource :user, path: 'settings', only: %i[show update destroy] do
    resources :characters, only: %i[index create update destroy], controller: :user_characters
  end

  root to: 'landing#index'
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pagy::Backend
  include Pundit

  after_action :verify_authorized, unless: -> { controller_name == 'sessions' }

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  add_flash_types :info, :error, :warning, :success, :list

  protected

  helper_method :rollout
  def rollout
    Rails.application.config.rollout
  end

  private

  def user_not_authorized(_exception)
    flash[:error] = 'You are not authorized to do that.'
    redirect_to(request.referer || root_path)
  end

  helper_method :current_nav
  def current_nav
    @current_nav || controller_name
  end

  def set_current(nav) # rubocop:disable Naming/AccessorMethodName
    @current_nav = nav.to_s
  end

  def append_info_to_payload(payload)
    super
    payload[:request_id] = request.uuid
    payload[:user_id] = current_user.id if current_user
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include Pagy::Frontend

  def current_user_image_url(size = 512)
    eve_character_image_url(current_user.main_character_id, size)
  end

  def eve_character_image_url(character_id, size = 512)
    "https://images.evetech.net/characters/#{character_id}/portrait?size=#{size}"
  end

  def current_nav?(nav)
    current_nav == nav
  end
end

app/views/application/_alerts.html.erb
<% if flash[:success].present? %>
  <%= render partial: 'shared/alert', locals: { color: 'green', text: flash[:success] } %>
<% elsif flash[:error].present? %>
  <%= render partial: 'shared/alert', locals: { color: 'red', text: flash[:error] } %>
<% elsif flash[:warning].present? %>
  <%= render partial: 'shared/alert', locals: { color: 'yellow', text: flash[:warning] } %>
<% end %>

app/views/application/_nav.html.erb
<header>
  <nav class="bg-gray-800">
    <div class="px-2 mx-auto max-w-7xl sm:px-6 lg:px-8">
      <div class="relative flex items-center justify-between h-16">
        <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
          <!-- Mobile menu button-->
          <button class="inline-flex items-center justify-center p-2 text-gray-400 rounded-md hover:text-white hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white" aria-expanded="false">
            <span class="sr-only">Open main menu</span>
            <!-- Icon when menu is closed. -->
            <!--
              Heroicon name: outline/menu

              Menu open: "hidden", Menu closed: "block"
            -->
            <svg class="block w-6 h-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
            </svg>
            <!-- Icon when menu is open. -->
            <!--
              Heroicon name: outline/x

              Menu open: "block", Menu closed: "hidden"
            -->
            <svg class="hidden w-6 h-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
        <div class="flex items-center justify-center flex-1 sm:items-stretch sm:justify-start">
          <div class="hidden sm:block sm:ml-6">
            <div class="flex space-x-4">
              <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
              <%= link_to 'Home', root_path, class: 'px-3 py-2 text-sm font-medium text-gray-300 rounded-md hover:bg-gray-700 hover:text-white' %>
              <%= link_to 'Logistics', root_path, class: 'px-3 py-2 text-sm font-medium text-gray-300 rounded-md hover:bg-gray-700 hover:text-white' %>
              <%= link_to 'Procurement', root_path, class: 'px-3 py-2 text-sm font-medium text-gray-300 rounded-md hover:bg-gray-700 hover:text-white' %>
              <%= link_to 'Reprocessing', root_path, class: 'px-3 py-2 text-sm font-medium text-gray-300 rounded-md hover:bg-gray-700 hover:text-white' %>
              <% if user_signed_in? %>
                <%= link_to 'Quotes', root_path, class: 'px-3 py-2 text-sm font-medium text-gray-300 rounded-md hover:bg-gray-700 hover:text-white' %>
                <%= link_to 'Orders', root_path, class: 'px-3 py-2 text-sm font-medium text-gray-300 rounded-md hover:bg-gray-700 hover:text-white' %>
              <% end %>
            </div>
          </div>
        </div>
        <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
          <% if user_signed_in? %>
            <button class="p-1 text-gray-400 bg-gray-800 rounded-full hover:text-white focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white">
              <span class="sr-only">View notifications</span>
              <!-- Heroicon name: outline/bell -->
              <svg class="w-6 h-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
              </svg>
            </button>

            <div class="relative ml-3"
              data-controller="dropdown"
              data-action="click->dropdown#toggle click@window->dropdown#hide"
              data-dropdown-active-target="#user-menu"
              data-dropdown-active-class=""
              data-dropdown-invisible-class="transform scale-95 opacity-0"
              data-dropdown-visible-class="transform scale-100 opacity-100"
              data-dropdown-entering-class="transition duration-100 ease-out"
              data-dropdown-enter-timeout="100"
              data-dropdown-leaving-class="transition duration-75 ease-in"
              data-dropdown-leave-timeout="75">
              <div id="user-menu">
                <button class="flex text-sm bg-gray-800 rounded-full focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white"
                  aria-haspopup="true" data-dropdown-target="button" role="button">
                  <span class="sr-only">Open user menu</span>
                  <%= image_tag current_user_image_url(64), class: 'w-8 h-8 rounded-full' %>
                </button>
                <div class="absolute right-0 hidden w-48 py-1 mt-2 transition origin-top-right transform scale-95 bg-white rounded-md shadow-lg opacity-0 ring-1 ring-black ring-opacity-5"
                  role="menu" aria-orientation="vertical" aria-labelledby="user-menu"
                  data-dropdown-target="menu">
                  <div class="bg-white">
                    <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100" role="menuitem">Your Profile</a>
                    <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100" role="menuitem">Settings</a>
                    <%= form_with url: destroy_user_session_path, method: :delete, class: 'block cursor-pointer hover:bg-gray-100' do |f| %>
                      <%= f.submit 'Log Out', class: 'block text-left w-full px-4 py-2 text-sm text-gray-700 cursor-pointer hover:bg-gray-100 bg-transparent outline-none focus:outline-none' %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          <% else %>
            <%= form_with url: user_customer_omniauth_authorize_path do |f| %>
              <%= f.submit 'Customer Login', type: :image, src: asset_pack_path('media/images/eve-sso-login-white-small.png') %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </nav>
</header>

app/views/application/_side_nav.html.erb
<!-- Static sidebar for desktop -->
<div class="hidden md:flex md:flex-shrink-0">
  <div class="flex flex-col w-64">
    <!-- Sidebar component, swap this element with another sidebar if you like -->
    <div class="flex flex-col flex-1 h-0">
      <div class="flex items-center flex-shrink-0 h-16 px-4 bg-gray-900">
        <%= image_pack_tag 'brave-logo.png', class: 'h-8 w-auto mx-auto' %>
      </div>
      <div class="flex flex-col flex-1 overflow-y-auto">
        <nav class="flex-1 px-2 py-4 space-y-1 bg-gray-800">
          <%= render partial: 'side_nav_link', locals: { current: current_nav?('dashboard'), text: 'Dashboard', icon: 'home', url: dashboard_path } %>
          <%= render partial: 'side_nav_link', locals: { current: current_nav?('series'), text: 'Series', icon: 'mail', url: series_index_path } %>
          <%= render partial: 'side_nav_link', locals: { current: current_nav?('corporations'), text: 'Corporations', icon: 'office-building', url: corporations_path } %>
          <%#= render partial: 'side_nav_link', locals: { current: current_nav?('reports'), text: 'Reports', icon: 'chart-bar', url: reports_path } %>
        </nav>
      </div>
    </div>
  </div>
</div>

app/views/application/_side_nav_link.html.erb
<% if current %>
  <%= link_to url, class: 'bg-gray-900 text-white group flex items-center px-2 py-2 text-sm font-medium rounded-md' do %>
    <%= render "icons/outline/#{icon}" %>
    <%= text %>
  <% end %>
<% else %>
  <%= link_to url, class: 'text-gray-300 hover:bg-gray-700 hover:text-white group flex items-center px-2 py-2 text-sm font-medium rounded-md' do %>
    <%= render "icons/outline/#{icon}" %>
    <%= text %>
  <% end %>
<% end %>

app/views/application/_top_nav.html.erb
<div class="relative z-10 flex flex-shrink-0 h-16 bg-white shadow">
  <button class="px-4 text-gray-500 border-r border-gray-200 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500 md:hidden">
    <span class="sr-only">Open sidebar</span>
    <!-- Heroicon name: outline/menu-alt-2 -->
    <svg class="w-6 h-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h7" />
    </svg>
  </button>
  <div class="flex justify-between flex-1 px-4">
    <div class="flex flex-1">
    </div>
    <div class="flex items-center ml-4 md:ml-6">
      <button class="p-1 text-gray-400 bg-white rounded-full hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
        <span class="sr-only">View notifications</span>
        <!-- Heroicon name: outline/bell -->
        <svg class="w-6 h-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
        </svg>
      </button>

      <!-- Profile dropdown -->
      <div class="relative ml-3" x-data="{ isOpen: false }">
        <div>
          <button type="button" class="flex items-center max-w-xs text-sm bg-white rounded-full focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" id="user-menu-button" aria-expanded="false" aria-haspopup="true" @click="isOpen = !isOpen">
            <span class="sr-only">Open user menu</span>
            <%= image_tag current_user_image_url(64), class: 'w-8 h-8 rounded-full' %>
          </button>
        </div>

        <!--
          Dropdown menu, show/hide based on menu state.

          Entering: "transition ease-out duration-100"
            From: "transform opacity-0 scale-95"
            To: "transform opacity-100 scale-100"
          Leaving: "transition ease-in duration-75"
            From: "transform opacity-100 scale-100"
            To: "transform opacity-0 scale-95"
        -->
        <div class="absolute right-0 w-48 py-1 mt-2 origin-top-right bg-white rounded-md shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1"
          x-show="isOpen"
          x-transition:enter="transition ease-out duration-100"
          x-transition:enter-start="transform opacity-0 scale-95"
          x-transition:enter-end="transform opacity-100 scale-100"
          x-transition:leave="transition ease-in duration-75"
          x-transition:leave-start="transform opacity-100 scale-100"
          x-transition:leave-end="transform opacity-0 scale-95"
        >
          <!-- Active: "bg-gray-100", Not Active: "" -->
          <!--
          <a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-0">Your Profile</a>

          <a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-1">Settings</a>
          -->
          <%= link_to 'Settings', user_path, class: 'block px-4 py-2 text-sm text-gray-700', role: 'menuitem', tabindex: '-1' %>

          <%= form_with url: destroy_user_session_path, class: 'block cursor-pointer hover:bg-gray-100', method: :delete do |f| %>
            <%= f.submit 'Log Out', class: 'block text-left w-full px-4 py-2 text-sm text-gray-700 cursor-pointer hover:bg-gray-100 bg-transparent outline-none focus:outline-none' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>