config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  authenticate :user, ->(u) { u.admin? } do
    mount PgHero::Engine => '/admin/postgres'
    mount Rollout::UI::Web.new => '/admin/rollout'
    mount Sidekiq::Web => '/admin/sidekiq'
  end

  namespace :admin do
    resources :alliances, only: %i[index show destroy]
    resources :characters, only: %i[index show destroy]
    resources :corporations, only: %i[index show destroy]
    resources :deliveries, only: %i[index show destroy]
    resources :users

    root to: 'dashboard#index'
  end

  devise_for :user, path: '', controllers: { omniauth_callbacks: 'oauth_callbacks' }
  devise_scope :user do
    delete 'auth/logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  get '/healthz', to: 'health#show', as: :health

  get '/dashboard', to: 'dashboard#index'

  resources :characters, only: %i[index show] do
    resources :progressions, only: %i[index show]
  end

  resources :corporations, only: %i[index show edit update], path_names: { edit: 'settings' } do
    resources :authorizations, only: %i[index destroy update], controller: :corporation_authorizations
    resources :members, only: %i[index], controller: :corporation_members
  end

  resources :series do
    member do
      delete :trash
      put :pause
      put :start
    end

    resources :steps, controller: :series_steps do
      member do
        put :move
      end
    end

    resources :subscriptions, controller: :series_subscriptions, only: %i[index show]
  end

  resource :user, path: 'settings', only: %i[show update destroy] do
    resources :characters, only: %i[index create update destroy], controller: :user_characters
  end

  root to: 'landing#index'
end

app/controllers/series_controller.rb
# frozen_string_literal: true

class SeriesController < AuthenticatedController
  before_action :find_series, only: %i[show edit update destroy]

  def index
    authorize(Series)
    @pagy, @series = pagy(current_user.accessible_series.kept.order(:name))
  end

  def new
    @series = authorize(Series.new)
  end

  def create
    @series = authorize(current_user.accessible_series.build(series_params.merge(trigger_quantifier: 'any',
                                                                                 status: 'active')))
    if @series.save
      flash[:success] = 'Series created successfully.'
      redirect_to series_path(@series)
    else
      render :new
    end
  end

  def show
    @pagy, @series_members = pagy(@series.series_members)
    @deliveries = @series.deliveries.where(member_id: @series_members.map(&:member_id))
  end

  def edit; end

  def update
    if @series.update(series_params)
      flash[:success] = 'Series updated successfully.'
      redirect_to series_path(@series)
    else
      render :edit
    end
  end

  def destroy
    @series.destroy
    flash[:success] = 'Series deleted successfully.'
    redirect_to series_path
  end

  def discard
    @series.discard
    flash[:success] = 'Series moved to trash.'
    redirect_to series_path
  end

  private

  def series_params
    params.require(:series).permit(:name, :kind, :description, :trigger_quantifier, :delivery_hour, :delivery_minute)
  end

  def find_series
    @series = authorize(current_user.series.find(params[:id]))
  end
end

app/helpers/series_helper.rb
# frozen_string_literal: true

module SeriesHelper
end

app/views/series/_form.html.erb
<div class="grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
  <div class="sm:col-span-6">
    <%= f.label :corporation_id, 'Corporation', class: 'block text-sm font-medium text-gray-700' %>
    <div class="mt-1">
      <%= f.collection_select :corporation_id, current_user.accessible_corporations, :id, :name, { prompt: true }, { class: 'mt-1 block w-full pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm rounded-md' } %>
    </div>
  </div>
  
  <div class="sm:col-span-6">
    <%= f.label :name, 'Name', class: 'block text-sm font-medium text-gray-700' %>
    <div class="mt-1">
      <%= f.text_field :name, class: 'appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm' %>
    </div>
  </div>

  <div class="sm:col-span-6">
    <%= f.label :description, 'Description', class: 'block text-sm font-medium text-gray-700' %>
    <div class="mt-1">
      <%= f.text_field :description, class: 'appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm' %>
    </div>
  </div>

  <div class="sm:col-span-1">
    <%= f.label :default_delivery_time, 'Delivery Window', class: 'block text-sm font-medium text-gray-700' %>
    <%= f.time_select :default_delivery_time, { minute_step: 15 }, class: 'mt-1 block w-full pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm rounded-md' %>
  </div>
</div>

app/views/series/_series_steps.html.erb
<div class="mt-6 overflow-hidden bg-white divide-y divide-gray-200 rounded-lg shadow">
  <div class="px-4 py-5 bg-white border-b border-gray-200 sm:px-6">
    <div class="flex flex-wrap items-center justify-between -mt-2 -ml-4 sm:flex-nowrap">
      <div class="mt-2 ml-4">
        <h3 class="text-lg font-medium leading-6 text-gray-900">
          Steps
        </h3>
      </div>
      <div class="flex-shrink-0 mt-2 ml-4">
        <%= link_to 'Add Step', new_campaign_step_path(@campaign), class: 'relative inline-flex items-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-gray-600 hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500' %>
      </div>
    </div>
  </div>
  <div class="px-4 py-5 sm:p-6">
    <div class="flow-root">
      <ul class="-mb-8">
        <% @campaign.steps.order(:position).each do |step| %>
          <li>
            <div class="relative pb-8">
              <% unless @campaign.steps.maximum(:position) == step.position %><span class="absolute top-4 left-4 -ml-px h-full w-0.5 bg-gray-200" aria-hidden="true"></span><% end %>
              <div class="relative flex space-x-3 items-center">
                <div class="min-w-0 flex-1 pt-1.5 flex justify-start space-x-4 items-center">
                  <div>
                    <% if step.kind == 'evemail' %>
                    <span class="flex items-center justify-center w-8 h-8 bg-green-400 rounded-full ring-8 ring-white">
                      <%= render partial: 'icons/solid/mail-open', locals: { w: 5, h: 5, color: 'white' } %>
                    </span>
                    <% elsif step.kind == 'delay' %>
                    <span class="flex items-center justify-center w-8 h-8 bg-blue-400 rounded-full ring-8 ring-white">
                      <%= render partial: 'icons/solid/clock', locals: { w: 5, h: 5, color: 'white' } %>
                    </span>
                    <% end %>
                  </div>
                  <div class="flex-grow">
                    <p class="text-sm text-gray-500"><a href="#" class="font-medium text-gray-900">
                      <% if step.kind == 'evemail' %><%= step.template.name %>
                      <% elsif step.kind == 'delay' %><%= pluralize(step.delay_days, 'day') %>
                      <% end %>
                    </a></p>
                  </div>
                  <div class="text-sm text-right text-gray-500 whitespace-nowrap">
                    <span class="relative z-0 inline-flex rounded-md shadow-sm">
                      <%= form_with model: step, url: campaign_step_path(@campaign, step) do |f| %>
                        <%= f.hidden_field :direction, value: 'down' %>
                        <%= f.button class: 'relative inline-flex items-center px-2 py-2 text-sm font-medium text-gray-500 bg-white border border-gray-300 rounded-l-md hover:bg-gray-50 focus:z-10 focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500' do %>
                          <span class="sr-only">Move down</span>
                          <%= render partial: 'icons/solid/chevron-down', locals: { w: 5, h: 5, color: 'gray' } %>
                        <% end %>
                      <% end %>
                      <%= form_with model: step, url: campaign_step_path(@campaign, step) do |f| %>
                        <%= f.hidden_field :direction, value: 'up' %>
                        <%= f.button class: 'relative inline-flex items-center px-2 py-2 text-sm font-medium text-gray-500 bg-white border border-gray-300 hover:bg-gray-50 focus:z-10 focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500' do %>
                          <span class="sr-only">Move up</span>
                          <%= render partial: 'icons/solid/chevron-up', locals: { w: 5, h: 5, color: 'gray' } %>
                        <% end %>
                      <% end %>
                      <%= link_to edit_campaign_step_path(@campaign, step), class: 'relative inline-flex items-center px-2 py-2 -ml-px text-sm font-medium text-gray-500 bg-white border border-gray-300 hover:bg-gray-50 focus:z-10 focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500' do %>
                        <span class="sr-only">Edit</span>
                        <%= render partial: 'icons/solid/pencil', locals: { w: 5, h: 5, color: 'gray' } %>
                      <% end %>
                      <%= form_with url: campaign_step_path(@campaign, step), html: { method: :delete } do |f| %>
                        <%= f.button class: 'relative inline-flex items-center px-2 py-2 text-sm font-medium text-gray-500 bg-white border border-gray-300 rrounded-r-md hover:bg-gray-50 focus:z-10 focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500' do %>
                          <span class="sr-only">Delete</span>
                          <%= render partial: 'icons/solid/x-circle', locals: { w: 5, h: 5, color: 'gray' } %>
                        <% end %>
                      <% end %>
                    </span>
                  </div>
                </div>
              </div>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/series/_series_subscriptions.html.erb
<div class="flex flex-col mt-6">
  <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
      <div class="overflow-hidden border-b border-gray-200 shadow sm:rounded-lg">
        <div class="px-4 py-5 bg-white border-b border-gray-200 sm:px-6">
          <div class="flex flex-wrap items-center justify-between -mt-4 -ml-4 sm:flex-nowrap">
            <div class="mt-4 ml-4">
              <h3 class="text-lg font-medium leading-6 text-gray-900">
                Subscriptions
              </h3>
            </div>
            <div class="flex-shrink-0 mt-4 ml-4">
            </div>
          </div>
        </div>
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase">
                Name
              </th>
              <th scope="col" class="px-6 py-3 text-xs font-medium tracking-wider text-left text-gray-500 uppercase">
                Added
              </th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
            <% @subscriptions.each do |subscription| %>
            <tr>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="flex items-center">
                  <div class="flex-shrink-0 w-10 h-10">
                    <%= image_tag eve_character_image_url(subscription.character_id, 64), class: 'h-10 w-10 rounded-full' %>
                  </div>
                  <div class="ml-4">
                    <div class="text-sm font-medium text-gray-900">
                      <%= link_to subscription.character_name, subscription_path(@series, subscription) %>
                    </div>
                  </div>
                </div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="text-sm text-gray-900"><%= time_tag subscription.created_at %></div>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <%= render partial: 'shared/pagination', locals: { pagy: @pagy } %>
      </div>
    </div>
  </div>
</div>

app/views/series/_series_summary.html.erb
<div class="overflow-hidden bg-white divide-y divide-gray-200 rounded-lg shadow">
  <div class="px-4 py-5 bg-white border-b border-gray-200 sm:px-6">
    <div class="flex flex-wrap items-center justify-between -mt-2 -ml-4 sm:flex-nowrap">
      <div class="mt-2 ml-4">
        <h3 class="text-lg font-medium leading-6 text-gray-900">
          <%= @campaign.name %>
        </h3>
      </div>
      <div class="flex-shrink-0 mt-2 ml-4">
        <%= link_to 'Edit', edit_campaign_path(@campaign), class: 'relative inline-flex items-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-gray-600 hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500' %>
        <%= form_with url: campaign_path, class: 'inline-block', html: { method: :delete } do |f| %>
          <%= f.submit 'Delete', class: 'relative inline-flex items-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-red-600 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500' %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="px-4 py-5 border-t border-gray-200 sm:p-0">
    <dl class="sm:divide-y sm:divide-gray-200">
      <div class="py-4 sm:py-5 sm:grid sm:grid-cols-6 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">
          Type
        </dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-5">
          <p>
            <span class="inline-flex items-center px-3 py-0.5 rounded-full text-sm font-medium bg-blue-100 text-blue-800">
              <%= Campaign::KINDS[@campaign.kind.to_sym] %>
            </span>
          </p>
        </dd>
      </div>
      <div class="py-4 sm:py-5 sm:grid sm:grid-cols-6 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">
          Description
        </dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-5">
          <p><%= @campaign.description %></code></p>
        </dd>
      </div>
      <div class="py-4 sm:py-5 sm:grid sm:grid-cols-6 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">
          Status
        </dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-5">
          <p>
            <% if @campaign.status == 'inactive' %>
              <span class="inline-flex items-center px-3 py-0.5 rounded-full text-sm font-medium bg-gray-100 text-gray-800">
                Inactive
              </span>
            <% elsif @campaign.status == 'active' %>
              <span class="inline-flex items-center px-3 py-0.5 rounded-full text-sm font-medium bg-red-100 text-red-800">
                Active
              </span>
            <% end %>
          </p>
        </dd>
      </div>
      <div class="py-4 sm:py-5 sm:grid sm:grid-cols-6 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">
          Delivery Window
        </dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-5">
          <p><%= @campaign.delivery_hour.to_s.rjust(2, '0') %>:<%= @campaign.delivery_minute.to_s.rjust(2, '0') %> EVE/UTC</p>
        </dd>
      </div>
    </dl>
  </div>
</div>

app/views/series/edit.html.erb
<%= render partial: 'shared/form_validations', locals: { model: @campaign } %>

<%= form_with model: @campaign do |f| %>
  <div class="bg-white overflow-hidden shadow rounded-lg divide-y divide-gray-200">
    <div class="px-4 py-5 sm:px-6">
      <h1 class="text-2xl font-bold text-gray-900">Edit Campaign</h1>
    </div>
    <div class="space-y-6 px-4 py-5 sm:p-6">
      <%= render partial: 'campaigns/form', locals: { f: f } %>
    </div>
    <div class="bg-gray-50 px-4 py-4 sm:px-6">
      <div class="text-right">
        <%= f.submit 'Save', class: 'inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500' %>
      </div>
    </div>
  </div>
<% end %>

app/views/series/index.html.erb
<div class="flex flex-col">
  <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
        <div class="bg-white px-4 py-5 border-b border-gray-200 sm:px-6">
          <div class="-ml-4 -mt-4 flex justify-between items-center flex-wrap sm:flex-nowrap">
            <div class="ml-4 mt-4">
              <h3 class="text-lg leading-6 font-medium text-gray-900">
                Series
              </h3>
              <p class="mt-1 text-sm text-gray-500">
              </p>
            </div>
            <div class="ml-4 mt-4 flex-shrink-0">
              <%= link_to 'New series', new_series_path, class: 'relative inline-flex items-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500' %>
            </div>
          </div>
        </div>
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Name
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Corporation
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Created
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Updated
              </th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
            <% @series.each do |series| %>
            <tr>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="text-sm text-gray-900"><%= link_to series.name, series_path(series) %></div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="text-sm text-gray-900"><%= link_to series.corporation.name, corporation_path(series.corporation) %></div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="text-sm text-gray-900"><%= time_tag series.created_at %></div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="text-sm text-gray-900"><%= time_tag series.updated_at %></div>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <%= render partial: 'shared/pagination', locals: { pagy: @pagy } %>
      </div>
    </div>
  </div>
</div>

app/views/series/new.html.erb
<%= render partial: 'shared/form_validations', locals: { model: @series } %>

<%= form_with model: @series do |f| %>
  <div class="bg-white overflow-hidden shadow rounded-lg divide-y divide-gray-200">
    <div class="px-4 py-5 sm:px-6">
      <h1 class="text-2xl font-bold text-gray-900">New Series</h1>
    </div>
    <div class="space-y-6 px-4 py-5 sm:p-6">
      <%= render partial: 'series/form', locals: { f: f } %>
    </div>
    <div class="bg-gray-50 px-4 py-4 sm:px-6">
      <div class="text-right">
        <%= f.submit 'Save', class: 'inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500' %>
      </div>
    </div>
  </div>
<% end %>

app/views/series/show.html.erb
<%= render partial: 'series/series_summary' %>

<%= render partial: 'series/series_steps' %>

<%= render partial: 'series/series_subscriptions' %>